version: '3'

services:
 app:
  build: .
  ports:
    - "80:80"
  depends_on:
    - minio
    - db

 db:
  image: postgres
  container_name: postgres
  restart: always
  environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  ports:
    - "5432:5432"
  volumes:
    - postgres:/var/lib/postgresql/data
 pgadmin:
  image: dpage/pgadmin4
  container_name: pgadmin4
  restart: always
  ports:
    - "5050:80"
  environment:
    PGADMIN_DEFAULT_EMAIL: katylubyankina@gmail.com
    PGADMIN_DEFAULT_PASSWORD: admin
  volumes:
    - pgadmin:/var/lib/pgadmin
  depends_on:
    - db

 minio:
  image: quay.io/minio/minio:latest
  hostname: minio
  command: minio server --console-address ":9090" /data
  ports:
    - ":9000:9000"
    - ":9090:9090"
  volumes:
    - minio:/var/lib/minio

volumes:
  postgres:
    driver: local
  minio:
    driver: local
  pgadmin:
    driver: local
